version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    ports:
      - "5432:5432"

  nats:
    image: nats-streaming:latest
    container_name: my_nats
    ports:
      - "4222:4222"
