CREATE TABLE myorder
(
    order_uid             serial,
    track_number          TEXT,
    entry                 TEXT,
    delivery_name         TEXT,
    delivery_phone        TEXT,
    delivery_zip          TEXT,
    delivery_city         TEXT,
    delivery_address      TEXT,
    delivery_region       TEXT,
    delivery_email        TEXT,
    payment_transaction   TEXT,
    payment_request_id    TEXT,
    payment_currency      TEXT,
    payment_provider      TEXT,
    payment_amount        TEXT,
    payment_dt            TEXT,
    payment_bank          TEXT,
    payment_delivery_cost TEXT,
    payment_goods_total   TEXT,
    payment_custom_fee    TEXT,
    items_chrt_id         INTEGER,
    items_track_number    TEXT,
    items_price           INTEGER,
    items_rid             TEXT,
    items_items_name      TEXT,
    items_items_sale      INTEGER,
    items_size            TEXT,
    items_total_price     INTEGER,
    items_nm_id           INTEGER,
    items_brand           TEXT,
    items_status          INTEGER,
    locale                TEXT,
    internal_signature    TEXT,
    customer_id           TEXT,
    delivery_service      TEXT,
    shardkey              TEXT,
    sm_id                 INTEGER,
    date_created          text,
    oof_shard             TEXT,
    PRIMARY KEY (order_uid)
);